# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://github.com/marketplace/actions/ssh-scp-ssh-pipelines

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go env -w CGO_ENABLED=0 && GOOS=linux GOARCH=amd64 go build -v ./...

      - name: Upload # 上传
        uses: alinz/ssh-scp-action@master
        env:
          LASTSSH: "Doing something after copying "
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          ssh_before: |-
            rm -rf /home/go-project/*
          scp: |-
              "./go-admin" => /home/go-project
          ssh_after: |-
            echo $LASTSSH
