# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

    - name: Upload
      uses: appleboy/scp-action@main
      with:
        host: ${{ secrets.REMOTE_HOST }} # 公网ip
        username: ${{ secrets.REMOTE_USERNAME }} # 用户名
        key: ${{ secrets.PRIVATE_KEY }} # 私钥
        source: "go-admin" # 发送文件
        target: "/home/go-project" # 目标目录